#!/bin/bash

# initialize dirs
mkdir -p ~/.vim/bundle
mkdir -p ~/.vim/colors

# vim colorscheme
cp tammela.vim ~/.vim/colors/

# git config
cp -i gitconfig ~/.gitconfig

# vimrc + vim plugins
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
cp -i vimrc ~/.vimrc
vim +PluginInstall +qall

# tmux + tmux plugins
mkdir -p ~/.tmux/plugins/tpm/
cp -R tpm/* ~/.tmux/plugins/tpm/
cp -i tmux.conf ~/.tmux.conf

# bash aliases
cp -i bash_aliases ~/.bash_aliases

# bash profile
cp -i bash_profile ~/.bash_profile
